modLoader="javafml" 

loaderVersion="[25,)" 

issueTrackerURL="http://my.issue.tracker/"

[[mods]] 

modId="rideon" 

version="1.1" 

displayName="RideOn" 

updateJSONURL="http://myurl.me/" 

displayURL="" 

logoFile="" 

credits=""

authors="MORIMORI0317" 

description='''
Thank you for downloading!

'''
