modLoader="javafml"
loaderVersion="[32,)" 
logoFile="logo.png" 
[[mods]]
modId="rideon"
version="${file.jarVersion}" 
displayName="Ride On"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rideon" 
authors="MORIMORI0317" 
description="Thank you for downloading!"
